global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  # ApiGateway metrics
  - job_name: "apigateway"
    static_configs:
      - targets: ["apigateway:8080"]
    metrics_path: "/metrics"
  
  # CustomerService metrics
  - job_name: "customer-service"
    static_configs:
      - targets: ["customerservice:8080"]
    metrics_path: "/metrics"
  
  # FraudService metrics
  - job_name: "fraud-service"
    static_configs:
      - targets: ["fraudservice:8080"]
    metrics_path: "/metrics"

  # TransactionService metrics
  - job_name: "transaction-service"
    static_configs:
      - targets: ["transactionservice:8080"]
    metrics_path: "/metrics"

  # WalletService metrics
  - job_name: "wallet-service"
    static_configs:
      - targets: ["walletservice:8080"]
    metrics_path: "/metrics"