global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  # CustomerService metrics
  - job_name: "customer-service"
    static_configs:
      - targets: ["host.docker.internal:5116"]  
    metrics_path: "/metrics"
  
  # FraudService metrics
  - job_name: "fraud-service"
    static_configs:
      - targets: ["host.docker.internal:5045"]  
    metrics_path: "/metrics"

  # TransactionService metrics
  - job_name: "trnsaction-service"
    static_configs:
      - targets: ["host.docker.internal:5068"]  
    metrics_path: "/metrics"

  # WalletService metrics
  - job_name: "wallet-service"
    static_configs:
      - targets: ["host.docker.internal:5212"]  
    metrics_path: "/metrics"